const User = require('../models/User')
const Post = require('../models/Post')

exports.register = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}


exports.logout = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}

exports.login = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}


// follow and unfollow
exports.followUser = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}


exports.updatePassword = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
    
}


exports.updateProfile = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}

exports.deleteMyProfile = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}



exports.myProfile = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}



exports.getUserProfile = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}


exports.getAllUsers = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}



exports.forgotPassword = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}



exports.resetPassword = async (req, res) => {
    try {
    } catch (error) {
        res.status(500).json({success: false, message: error.message})
    }
}